title: Iglesia Cuadrangular de Venezuela
email: admin@iglesiacuadrangular.com.ve
description: Iglesia Cristiana Cuadrangular de Venezuela
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iglesiacuadrangular.com.ve" # the base hostname & protocol for your site, e.g. http://example.com

baseurl: ""
disqus: IglesiaCuadrangular
google_analytics: UA-60076044-6

facebook:
    app_id: 467818103369447
    version: v3.2

author: Iglesia Cuadrangular
logo: /images/logo.png
lang: es
markdown: kramdown
remote_theme: IglesiaCristianaCuadrangular/jekyll-theme-cuadrangular
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
